// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdfns81U2Afd4RoXkJwq42EJNdBFtVaDI',
    appId: '1:604308214208:web:f0b6fecfead7c95ac7f825',
    messagingSenderId: '604308214208',
    projectId: 'smart-canteen-1ba1c',
    authDomain: 'smart-canteen-1ba1c.firebaseapp.com',
    storageBucket: 'smart-canteen-1ba1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkABlIwZ7_tbB1aDQYZ4-Nlgh_afMwvzI',
    appId: '1:604308214208:android:a7326d0dad3945a4c7f825',
    messagingSenderId: '604308214208',
    projectId: 'smart-canteen-1ba1c',
    storageBucket: 'smart-canteen-1ba1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKRNO0KroPabA7ORkRC36rVLIigQMxo_8',
    appId: '1:604308214208:ios:a64d80e6ea052481c7f825',
    messagingSenderId: '604308214208',
    projectId: 'smart-canteen-1ba1c',
    storageBucket: 'smart-canteen-1ba1c.firebasestorage.app',
    iosBundleId: 'com.example.smartCanteen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKRNO0KroPabA7ORkRC36rVLIigQMxo_8',
    appId: '1:604308214208:ios:a64d80e6ea052481c7f825',
    messagingSenderId: '604308214208',
    projectId: 'smart-canteen-1ba1c',
    storageBucket: 'smart-canteen-1ba1c.firebasestorage.app',
    iosBundleId: 'com.example.smartCanteen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdfns81U2Afd4RoXkJwq42EJNdBFtVaDI',
    appId: '1:604308214208:web:48f95e5f42ee0a59c7f825',
    messagingSenderId: '604308214208',
    projectId: 'smart-canteen-1ba1c',
    authDomain: 'smart-canteen-1ba1c.firebaseapp.com',
    storageBucket: 'smart-canteen-1ba1c.firebasestorage.app',
  );
}
