// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfs55tDxGvWYy8nMVKAPcNSiGCbqnlFYI',
    appId: '1:366474388313:web:463b1b7ad1afe46679e248',
    messagingSenderId: '366474388313',
    projectId: 'fir-tutorial-e42dc',
    authDomain: 'fir-tutorial-e42dc.firebaseapp.com',
    storageBucket: 'fir-tutorial-e42dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxkPr2dKdAKk1BDyLTqArUki51kyXjzNw',
    appId: '1:366474388313:android:572545df41cda8e979e248',
    messagingSenderId: '366474388313',
    projectId: 'fir-tutorial-e42dc',
    storageBucket: 'fir-tutorial-e42dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD2B4bFkeMKndwLunv1MyAujm1_Q8IiRk',
    appId: '1:366474388313:ios:c168d50b6d004d6c79e248',
    messagingSenderId: '366474388313',
    projectId: 'fir-tutorial-e42dc',
    storageBucket: 'fir-tutorial-e42dc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD2B4bFkeMKndwLunv1MyAujm1_Q8IiRk',
    appId: '1:366474388313:ios:c168d50b6d004d6c79e248',
    messagingSenderId: '366474388313',
    projectId: 'fir-tutorial-e42dc',
    storageBucket: 'fir-tutorial-e42dc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfs55tDxGvWYy8nMVKAPcNSiGCbqnlFYI',
    appId: '1:366474388313:web:9c6e910bbe094e3779e248',
    messagingSenderId: '366474388313',
    projectId: 'fir-tutorial-e42dc',
    authDomain: 'fir-tutorial-e42dc.firebaseapp.com',
    storageBucket: 'fir-tutorial-e42dc.firebasestorage.app',
  );
}
